/**
 * C++ VR Application for Audio Transcription and Analysis
 * 
 * This application transcribes audio files using OpenAI's Whisper API,
 * analyzes the transcription using GPT-4o to categorize the content,
 * and sends the categorized data to a Notion database.
 * 
 * The application handles:
 * 1. Audio file selection
 * 2. Transcription via OpenAI Whisper API
 * 3. Content analysis via OpenAI GPT-4o
 * 4. Notion database integration with proper property types
 */

// Include necessary libraries
#include <iostream>     // Standard I/O operations for console output
#include <fstream>      // File stream handling for reading audio files
#include <string>       // String manipulation for text processing

#include <cstdlib>      // Standard library functions, e.g., exit()
#include <unistd.h>     // For access() function to check file existence
#include <sstream>      // String stream operations for string manipulation

#include <regex>        // Regular expressions for pattern matching




// Include the nlohmann/json library for JSON parsing and manipulation
#include "nlohmann/json.hpp"
// Include the configuration file for API keys
#include "config.h"
#include "transcription.h"
#include "analysis.h"
#include "notion.h"
using json = nlohmann::json;
using namespace std;


/**
 * Function to prompt the user to select an audio file
 * 
 * This function displays a prompt asking the user to enter the path to an audio file.
 * It validates that the file exists before returning the path.
 * The user can type 'exit' to quit the application.
 * 
 * @return The path to the selected audio file
 */
string getFileFromDialog() {
    string filePath;
    bool validFile = false;
    while (!validFile) {
        cout << "Please enter the full patcd /Users/root1/C++/VRapp/C++_VR_App.cpph to your audio file (or type 'exit' to quit): ";
        getline(cin, filePath);
        if (filePath == "exit") {
            exit(EXIT_SUCCESS);
        }
        if (access(filePath.c_str(), F_OK) != 0) {
            cerr << "File does not exist. Please check the path and try again." << endl;
        } else {
            validFile = true;
        }
    }
    return filePath;
}


/**
 * Main function - Entry point of the application
 * 
 * This function:
 * 1. Prompts the user to select an audio file
 * 2. Transcribes the audio using OpenAI's Whisper API
 * 3. Analyzes the transcription using GPT-4o
 * 4. Sends the categorized data to a Notion database
 * 
 * @return 0 on successful execution
 */// Function to convert JSON data to LaTeX format
string convertToLatex(const nlohmann::json &data) {
    ostringstream latex;
    
    // Start the LaTeX document
    latex << "\\documentclass{article}\n";
    latex << "\\usepackage{geometry}\n";
    latex << "\\usepackage{enumitem}\n";
    latex << "\\usepackage{hyperref}\n";
    latex << "\\usepackage{xcolor}\n";
    latex << "\\usepackage{titlesec}\n";
    latex << "\\usepackage{fancyhdr}\n";
    latex << "\\usepackage{booktabs}\n";
    
    // Set up the document
    latex << "\\geometry{margin=1in}\n";
    latex << "\\titleformat{\\section}{\\normalfont\\Large\\bfseries}{\\thesection}{1em}{}\n";
    latex << "\\pagestyle{fancy}\n";
    latex << "\\fancyhf{}\n";
    latex << "\\renewcommand{\\headrulewidth}{0pt}\n";
    latex << "\\fancyfoot[C]{\\thepage}\n";
    
    // Begin the document
    latex << "\\begin{document}\n\n";
    
    // Add the title
    if (data.contains("Summary")) {
        string summary = data["Summary"].is_string() ? data["Summary"].get<string>() : data["Summary"].dump();
        latex << "\\title{" << summary << "}\n";
        latex << "\\author{Generated by AI Analysis}\n";
        latex << "\\date{\\today}\n";
        latex << "\\maketitle\n\n";
    }
    
    // Add metadata section
    latex << "\\section*{Metadata}\n";
    latex << "\\begin{tabular}{ll}\n";
    latex << "\\toprule\n";
    
    // Add Type
    if (data.contains("Type")) {
        string type = data["Type"].is_string() ? data["Type"].get<string>() : data["Type"].dump();
        latex << "Type & " << type << " \\\\\n";
    }
    
    // Add Duration
    if (data.contains("Duration")) {
        string duration = data["Duration"].is_string() ? data["Duration"].get<string>() : data["Duration"].dump();
        latex << "Duration & " << duration << " \\\\\n";
    }
    
    // Add AI Cost
    if (data.contains("AI Cost")) {
        string cost = data["AI Cost"].is_string() ? data["AI Cost"].get<string>() : data["AI Cost"].dump();
        latex << "AI Cost & " << cost << " \\\\\n";
    } else if (data.contains("At Cost")) {
        string cost = data["At Cost"].is_string() ? data["At Cost"].get<string>() : data["At Cost"].dump();
        latex << "AI Cost & " << cost << " \\\\\n";
    }
    
    // Add Date
    if (data.contains("Date")) {
        string date = data["Date"].is_string() ? data["Date"].get<string>() : data["Date"].dump();
        latex << "Date & " << date << " \\\\\n";
    }
    
    // Add Icon
    if (data.contains("Icon")) {
        string icon = data["Icon"].is_string() ? data["Icon"].get<string>() : data["Icon"].dump();
        latex << "Icon & " << icon << " \\\\\n";
    }
    
    latex << "\\bottomrule\n";
    latex << "\\end{tabular}\n\n";
    
    // Add Main Points section
    if (data.contains("Main Points")) {
        latex << "\\section{Main Points}\n";
        latex << "\\begin{itemize}[leftmargin=*]\n";
        
        if (data["Main Points"].is_array()) {
            for (const auto& point : data["Main Points"]) {
                string pointText = point.is_string() ? point.get<string>() : point.dump();
                latex << "  \\item " << pointText << "\n";
            }
        } else {
            string mainPoints = data["Main Points"].is_string() ? data["Main Points"].get<string>() : data["Main Points"].dump();
            latex << "  \\item " << mainPoints << "\n";
        }
        
        latex << "\\end{itemize}\n\n";
    }
    
    // Add Action Items section
    if (data.contains("Action Items")) {
        latex << "\\section{Action Items}\n";
        latex << "\\begin{itemize}[leftmargin=*]\n";
        
        if (data["Action Items"].is_array()) {
            for (const auto& item : data["Action Items"]) {
                string itemText = item.is_string() ? item.get<string>() : item.dump();
                latex << "  \\item " << itemText << "\n";
            }
        } else {
            string actionItems = data["Action Items"].is_string() ? data["Action Items"].get<string>() : data["Action Items"].dump();
            latex << "  \\item " << actionItems << "\n";
        }
        
        latex << "\\end{itemize}\n\n";
    }
    
    // Add Follow-up Questions section
    if (data.contains("Follow-up Questions")) {
        latex << "\\section{Follow-up Questions}\n";
        latex << "\\begin{itemize}[leftmargin=*]\n";
        
        if (data["Follow-up Questions"].is_array()) {
            for (const auto& question : data["Follow-up Questions"]) {
                string questionText = question.is_string() ? question.get<string>() : question.dump();
                latex << "  \\item " << questionText << "\n";
            }
        } else {
            string questions = data["Follow-up Questions"].is_string() ? data["Follow-up Questions"].get<string>() : data["Follow-up Questions"].dump();
            latex << "  \\item " << questions << "\n";
        }
        
        latex << "\\end{itemize}\n\n";
    }
    
    // Add Arguments section
    if (data.contains("Arguments")) {
        latex << "\\section{Arguments}\n";
        
        if (data["Arguments"].is_object()) {
            for (auto& [key, value] : data["Arguments"].items()) {
                string argTitle = key;
                string argContent = value.is_string() ? value.get<string>() : value.dump();
                
                latex << "\\subsection*{" << argTitle << "}\n";
                latex << argContent << "\n\n";
            }
        } else if (data["Arguments"].is_array()) {
            latex << "\\begin{itemize}[leftmargin=*]\n";
            for (const auto& arg : data["Arguments"]) {
                string argText = arg.is_string() ? arg.get<string>() : arg.dump();
                latex << "  \\item " << argText << "\n";
            }
            latex << "\\end{itemize}\n\n";
        } else {
            string arguments = data["Arguments"].is_string() ? data["Arguments"].get<string>() : data["Arguments"].dump();
            latex << arguments << "\n\n";
        }
    }
    
    // Add References section
    if (data.contains("References")) {
        latex << "\\section{References}\n";
        latex << "\\begin{itemize}[leftmargin=*]\n";
        
        if (data["References"].is_array()) {
            for (const auto& ref : data["References"]) {
                string refText = ref.is_string() ? ref.get<string>() : ref.dump();
                latex << "  \\item " << refText << "\n";
            }
        } else {
            string references = data["References"].is_string() ? data["References"].get<string>() : data["References"].dump();
            latex << "  \\item " << references << "\n";
        }
        
        latex << "\\end{itemize}\n\n";
    }
    
    // Add Stories section
    if (data.contains("Stories")) {
        latex << "\\section{Stories}\n";
        latex << "\\begin{itemize}[leftmargin=*]\n";
        
        if (data["Stories"].is_array()) {
            for (const auto& story : data["Stories"]) {
                string storyText = story.is_string() ? story.get<string>() : story.dump();
                latex << "  \\item " << storyText << "\n";
            }
        } else {
            string stories = data["Stories"].is_string() ? data["Stories"].get<string>() : data["Stories"].dump();
            latex << "  \\item " << stories << "\n";
        }
        
        latex << "\\end{itemize}\n\n";
    }
    
    // Add Sentiment section
    if (data.contains("Sentiment")) {
        latex << "\\section{Sentiment}\n";
        string sentiment = data["Sentiment"].is_string() ? data["Sentiment"].get<string>() : data["Sentiment"].dump();
        latex << sentiment << "\n\n";
    }
    
    // End the document
    latex << "\\end{document}\n";
    
    return latex.str();
}

// Function to save LaTeX to a file
bool saveLatexToFile(const string &latex, const string &filePath) {
    ofstream file(filePath);
    if (!file.is_open()) {
        cerr << "Failed to open file for writing: " << filePath << endl;
        return false;
    }
    
    file << latex;
    file.close();
    
    cout << "LaTeX saved to: " << filePath << endl;
    return true;
}
int main() {
    cout << "Select an audio file for transcription." << endl;
    string filePath = getFileFromDialog();
    
    // Use the API key from the config file
    string apiKey = OPENAI_API_KEY;
    
    // Transcribe audio
    cout << "Transcribing audio file: " << filePath << "..." << endl;
    string transcriptionResponse = transcribeAudio(filePath, apiKey);
    
    // Parse the transcription JSON to extract the transcription text
    string transcriptionText;
    try {
        auto jsonResponse = json::parse(transcriptionResponse);
        // Assuming the transcription text is in the "text" field
        transcriptionText = jsonResponse["text"];
        cout << "Transcription:" << endl << transcriptionText << endl;
    } catch (const exception& e) {
        cerr << "Error parsing transcription JSON response: " << e.what() << endl;
        cout << "Raw transcription response:" << endl << transcriptionResponse << endl;
        transcriptionText = transcriptionResponse; // Fallback to raw response if parsing fails
    }
    
    // Process transcription with the Chat Completions API
    cout << "Processing transcription with OpenAI Chat Completions API..." << endl;
    string categorizedResponse = categorizeWithOpenAI(transcriptionText, apiKey);
    
    // Parse the categorized JSON response to extract the assistant's reply
    nlohmann::json categorizedJson;
    string assistantReply;
    
    try {
        auto jsonResponse = json::parse(categorizedResponse);
        // Chat completions responses usually include a "choices" array
        assistantReply = jsonResponse["choices"][0]["message"]["content"];
        cout << "Categorized Response:" << endl << assistantReply << endl;
        
        // Extract JSON from code block if present
        try {
            // Check if the response is wrapped in a code block
            regex jsonBlockPattern("```json\\s*([\\s\\S]*?)\\s*```");
            smatch matches;
            if (regex_search(assistantReply, matches, jsonBlockPattern) && matches.size() > 1) {
                // Extract the JSON content from the code block
                string jsonContent = matches[1].str();
                categorizedJson = json::parse(jsonContent);
            } else {
                // Try parsing directly if not in a code block
                categorizedJson = json::parse(assistantReply);
            }
            
            cout << "Parsed JSON successfully" << endl;
        } catch (const exception& e) {
            cerr << "Error parsing categorized JSON: " << e.what() << endl;
            // Fallback to example JSON if parsing fails
            categorizedJson = {
                {"Summary", "This is a brief summary."},
                {"Main Points", "Point A, Point B, Point C"},
                {"Action Items", "Follow up on item 1 and item 2"},
                {"Follow-up Questions", "What is the timeline?"},
                {"Stories", "A brief anecdote..."},
                {"References", "Reference details here"},
                {"Arguments", "The arguments are..."},
                {"Sentiment", "Positive"}
            };
            cout << "Using fallback JSON example" << endl;
        }
    } catch (const exception& e) {
        cerr << "Error parsing chat completions JSON response: " << e.what() << endl;
        cout << "Raw categorized response:" << endl << categorizedResponse << endl;
        // Fallback to example JSON if parsing fails
        categorizedJson = {
            {"Summary", "This is a brief summary."},
            {"Main Points", "Point A, Point B, Point C"},
            {"Action Items", "Follow up on item 1 and item 2"},
            {"Follow-up Questions", "What is the timeline?"},
            {"Stories", "A brief anecdote..."},
            {"References", "Reference details here"},
            {"Arguments", "The arguments are..."},
            {"Sentiment", "Positive"}
        };
        cout << "Using fallback JSON example" << endl;
    }
    
    // Use the API keys from the config file
    string notionDatabaseId = NOTION_DATABASE_ID;
    string notionApiKey = NOTION_API_KEY;

    if (sendToNotion(categorizedJson, notionDatabaseId, notionApiKey)) {
        cout << "Data successfully sent to Notion." << endl;
    } else {
        cerr << "Failed to send data to Notion." << endl;
    }
    // Convert the JSON to LaTeX
    string latex = convertToLatex(categorizedJson);
    
    // Save the LaTeX to a file
    string latexFilePath = "transcription_analysis.tex";
    if (saveLatexToFile(latex, latexFilePath)) {
        cout << "LaTeX output saved to " << latexFilePath << endl;
        
        // Compile the LaTeX file to PDF (if pdflatex is available)
        string compileCommand = "pdflatex " + latexFilePath;
        cout << "You can compile the LaTeX file to PDF using: " << compileCommand << endl;
    } else {
        cerr << "Failed to save LaTeX output." << endl;
    }    
    return 0;
}
