
# Use the official Node.js image
FROM node:18

# Create and change to the app directory
WORKDIR /usr/src/app

# Copy application dependency manifests to the container image
COPY web/client/package*.json ./

# Install dependencies
RUN npm install

# Copy local code to the container image
COPY web/client/. .

# Run the app
CMD [ "npm", "start" ]
